#!/bin/bash

# Copyright (c) 2014, Luis Cruz (AxDev Developers).

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# First run (for autoinstall):
#     cd path/to/optimize_png
#     sudo ./optimize_png <path to PNG, if desired>
# This downloads, builds (OptiPNG) and installs the required tools
# to run this script to /usr/local/bin.
# NOTE: export CC can be set before make install to compile OptiPNG
# with desired toolchain.

# Usage: optimize_png -a OR optimize_png /path/to/file.png
#     Where '-a' does all PNGs recursively under the current dir.
# Tip: Add to PATH.

PNG_PATH=$@;
OPTIPNG_VER=0.7.5;
OPTIPNG_SHA1=30b6c333d74fc0f5dc83004aace252fa3321368b;
PNGOUT_SHA1=37514b337adb672d982b4f98668b0300f177d8d2;

while getopts ":a" opt
do
    input_png=$(echo "$@" | sed "s/-$opt//")
    case "$opt" in
        a)
             PNG_PATH=$(find . -name \*.png)"$input_png";;
        *)
             break;;
    esac
done

# OptiPNG autoinstall
if ! type optipng &>/dev/null; then
    MISSING_TOOL=true;
    echo "OptiPNG is not installed...";
    echo "";
    if [ `whoami` != "root" ]; then
        echo "Run as root for automatic install or install from";
        echo "http://sourceforge.net/projects/optipng/";
        echo "";
    else
        echo "Automatic install will begin in 3 seconds...";
        sleep 3;
        if [ ! -d "optipng-$OPTIPNG_VER" ]; then
            until [ "$optar_sha1" == "$OPTIPNG_SHA1" ]; do
                echo "Downloading & extracting OptiPNG source tar...";
                wget http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-$OPTIPNG_VER/optipng-$OPTIPNG_VER.tar.gz;
                optar_sha1=`sha1sum "optipng-$OPTIPNG_VER.tar.gz" | sed 's/ .*//'`;
                if [ "$optar_sha1" != "$OPTIPNG_SHA1" ]; then
                    echo "SHA-1 checksum does not match! Redownloading...";
                    rm -rf optipng-$OPTIPNG_VER.tar.gz;
                fi
            done
            tar xf optipng-$OPTIPNG_VER.tar.gz;
            rm -rf optipng-$OPTIPNG_VER.tar.gz;
        fi
        echo "Installing optipng-$OPTIPNG_VER.";
        cd optipng-$OPTIPNG_VER;
        ./configure;
#       export CC=~/gcc-toolchains/arm-none-linux-gnueabi-4.8.3/bin/arm-none-linux-gnueabi;
        make install;
        cd ..;
        if type optipng &>/dev/null; then
            MISSING_TOOL=false;
            rm -rf optipng-$OPTIPNG_VER;
            echo "OptiPNG installed successfully.";
            echo "";
        else
            echo "Something went wrong. OptiPNG not installed.";
            echo "";
        fi
    fi
fi

# PNGOUT autoinstall
if ! type pngout &>/dev/null; then
    MISSING_TOOL=true;
    echo "PNGOUT is not installed...";
    echo "";
    if [ `whoami` != "root" ]; then
        echo "Run as root for automatic install or install from";
        echo "http://jonof.id.au/kenutils";
        echo "";
    else
        echo "Automatic install will begin in 3 seconds...";
        sleep 3;
        if [ ! -d "pngout-20130221-linux" ]; then
            until [ "$potar_sha1" == "$PNGOUT_SHA1" ]; do
                echo "Downloading & extracting PNGOUT tar...";
                wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz;
                potar_sha1=`sha1sum "pngout-20130221-linux.tar.gz" | sed 's/ .*//'`;
                if [ "$potar_sha1" != "$PNGOUT_SHA1" ]; then
                    echo "SHA-1 checksum does not match! Redownloading...";
                    rm -rf pngout-20130221-linux.tar.gz;
                fi
            done
            tar xf pngout-20130221-linux.tar.gz;
            rm -rf pngout-20130221-linux.tar.gz;
        fi
        arch=$(uname -m)
        if [ -d "pngout-20130221-linux/$arch" ]; then
            echo "Installing $arch pngout.";
            cp pngout-20130221-linux/$arch/pngout /usr/local/bin/pngout;
        else
            echo "PNGOUT does not support $arch.";
        fi
        if type pngout &>/dev/null; then
            MISSING_TOOL=false;
            rm -rf pngout-20130221-linux;
            echo "PNGOUT installed successfully.";
            echo "";
        else
            echo "Something went wrong. PNGOUT not installed.";
            echo "";
        fi
    fi
fi

if [ "$MISSING_TOOL" == true ]; then
    echo "Install OptiPNG and/or PNGOUT and try again.";
elif [ "$PNG_PATH" ]; then
    for png_file in $PNG_PATH; do
        if [ -f "$png_file" ]; then
            echo "Optimizing PNG using OptiPNG for reduction...";
            optipng -o5 -strip all $png_file;
            echo "Compressing PNG with KS-Flate compression using PNGOUT...";
            pngout -f6 -kp -ks $png_file;
        else
            echo "Invalid target png: $png_file";
            break;
        fi
    done
else
    echo "No target png.";
fi
